baseURL = 'https://krishna-bhandari.com.np/'
languageCode = 'en-us'
title = 'Krishna Bhandari'
theme = 'paper'
googleAnalytics = "G-29GSFNCWRD"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'krishna8723'               # twitter.com/YOUR_TWITTER_ID
  github = 'krishnahimself'                 # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'YOUR_LINKEDIN_ID'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/19906424?v=4'                 # gravatar email or image url
  name = 'Krishna Bhandari'
  bio = 'Senior Software Engineer'

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 10


  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally

  # giscus
[params.giscus]
  repo = 'krishnahimself/krishnahimself.github.io'                 # see https://giscus.app for more details
  repoId = 'R_kgDOLbEWlA'
  category = 'General'
  categoryId = 'DIC_kwDOLbEWlM4Cl7Md'
  mapping = 'pathname'
  theme = 'light'
  lang = 'en'
